---
title: "ei2262_assignment4"
output:
  html_document: default
editor_options:
  chunk_output_type: inline
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(stats)
library(factoextra)
library(cluster)
```

### Part 1: Implementing a Simple Prediction Pipeline

# Loading in class4_p1.csv Dataset
```{r}
class4_p1<-read.csv("./class4_p1.csv", header=TRUE)

colnames(class4_p1)[1] ="patcid"

#Checking the variable types
str(class4_p1)

#Converting categorical variables into factors
class4_p1$chronic1<-as.factor(class4_p1$chronic1)
class4_p1$chronic3<-as.factor(class4_p1$chronic3)
class4_p1$chronic4<-as.factor(class4_p1$chronic4)
class4_p1$tobacco1<-as.factor(class4_p1$tobacco1)
class4_p1$alcohol1<-as.factor(class4_p1$alcohol1)
class4_p1$habits5<-as.factor(class4_p1$habits5)
class4_p1$habits7<-as.factor(class4_p1$habits7)
class4_p1$agegroup<-as.factor(class4_p1$agegroup)
class4_p1$dem3<-as.factor(class4_p1$dem3)
class4_p1$dem4<-as.factor(class4_p1$dem4)
class4_p1$dem8<-as.factor(class4_p1$dem8)
class4_p1$povertygroup<-as.factor(class4_p1$povertygroup)

str(class4_p1)
```



